name: geziyoruz
favicon: null
layout_spectrum: 0.77077
typography_spectrum: 0.44083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1cfc3'
    - '#3f5a6f'
    - '#fef5ee'
    - '#908f8b'
    - '#e77978'
  brandStrength: 0.5
  lightness: 0.7908075076993555
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
