name: geziyoruz
favicon: null
layout_spectrum: 0.5590521276462823
typography_spectrum: 0.906310994643718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6666544938925654
  lightness: 0.7908075076993555
  saturation: 0.34350302489474416
  rhythmicContrast: 0.3531009473372251
purpose: []
